### ISSUE TITLE
Bug in release 1.6

### ISSUE THREAD

**Issue by froudaut** [jkboyce/jugglinglab#107]
An error window occurs when we want to run SS in v1.6.
I get this on Windows 7/10 and Linux. 
I send you an email to the address you provide in the JL GUI with related snapshots and some other possible features that could be added. I do not think such list/email is relevant in the gitlab discussion but perhaps . 
Regards

**Comment by jkboyce** [comment]
Thanks @froudaut -- you found a breaking bug in the French and Portuguese versions. It should be fixed now in version 1.6.1.
