### ISSUE TITLE
Save/load JML in previous location

### ISSUE THREAD

**Issue by hapiel** [jkboyce/jugglinglab#118]
Just a tiny annoyance, but every time I open up Juggling Lab and I go to browse for a pattern it takes me to the default folder, my user folder on windows. Which is very very far removed from the actual folder where I store jml files.

I would really like it to remember my last used folder even if I open and close the software, that would save me a lot of clicks!

**Comment by jkboyce** [comment]
Hi @hapiel , this was a good suggestion and an easy fix. Will be in the next release!

Change committed to main branch, closing the issue.
