### ISSUE TITLE
Pattern: "[2T3]", Dwell beats="0.4", press "Juggle"> total crash

### ISSUE THREAD

**Issue by santropedro** [jkboyce/jugglinglab#124]
Bug:
My setup: Windows 10, laptop Lenovo 2016 pretty ordinary, I tried this problem before and after installing (as you recommend in https://jugglinglab.org/, maybe it's not related to this bug, but I tried it to rule it out) Microsoft Visual C++ Redistributable for Visual Studio 2019, and restarting so it worked, but it persists.

How to reproduce the bug:
Run juggling lab
Fill "Pattern" with [2T3], fill Dwell beats: with "0.4" (you can also put "0.1", "0.25", or I believe any number <=0.4, weirdly 0.5, 0.6 doesn't bug as with many greater numbers that I tried), click "Juggle", then "Juggling lab" window (the obvious one, the first that opens when running the program) immediately crashes/freezes, absolutely not responding, (also doesn't open a new window with the animation we always have). I'm then forced to close it with task admin.

I'll report future patterns that also crash it.

**Comment by jkboyce** [comment]
I've reproduced the issue. Thanks for reporting! @santropedro I believe you have the distinction of being first to report a bug that completely hangs the program.

**Comment by santropedro** [comment]
@jkboyce 1) There are no words to express how awesome this whole project you make (with others you credited), it's really mega super great. 2) btw, I just downloaded this new version 1.6.3 (in chrome, under the same normal conditions I always use), and in my machine it says "virus detected". Of course, maybe it's only my machine and not others, I just mention it in case it happens to someone else, I'll try to download it and run it in the following days (but with caution) to see if it works and report back.

**Comment by jkboyce** [comment]
Hi @santropedro , thanks for reporting! Windows Defender sometimes flags installers created with Inno Setup as potential viruses. In this case I know it isn't a virus, but Defender makes mistakes.

The best solution is to digitally sign the installer exe, but the cheapest certificate is around $100/yr. I have the same issue with the macOS version; Apple wants $100/yr to be able to digitally sign code. The new [sigstore](https://www.sigstore.dev/) project looks promising.

**Comment by jkboyce** [comment]
Moving to a new issue

**Comment by santropedro** [comment]
I just installed JugglingLab both in Windows 10 and Ubuntu 22 LTS, I confirm (not that anyone asked me, however for what it's worth, I say it, feel free to delete my comments if it clutters things) the title/main issue no longer happens in Windows to me (awesome!), and neither in Ubuntu (great!), in which I tested the same bug conditions as the original bug, and it also didn't bug (I have no idea if it did before 1.6.3, because I installed Ubuntu today).
