### ISSUE TITLE
Feature suggestion: Visualize entire hand path when editing events

### ISSUE THREAD

**Issue by jkboyce** [jkboyce/jugglinglab#126]
"Might it be an idea to have a toggle to be able to visualize the hand path curve? Like the curve for the whole loop? That way it would perhaps be easier to modify the hand path, because when you edit a single node you immediately see how that influences the complete path the hand traces."

_Originally posted by @hapiel in https://github.com/jkboyce/jugglinglab/issues/99#issuecomment-1053471560_

**Comment by jkboyce** [comment]
Implemented in version 1.6.4

**Comment by hapiel** [comment]
This is amazing, thanks! Awesome work, and looks great!

**Comment by jkboyce** [comment]
Thanks! And thank you for the suggestion, the idea had never occurred to me before.
