### ISSUE TITLE
Bringing Juggling Lab back to the web

### ISSUE THREAD

**Issue by rkaravia** [jkboyce/jugglinglab#57]
Hello & thank you for making Juggling Lab! I don't know when I first used it, but certainly already before I made [this video](https://www.youtube.com/watch?v=6ZGA017n5jk) in 2007.

I just saw that there thing called [CheerpJ](https://www.leaningtech.com/cheerpj/) that compiles Java bytecode to JavaScript, so it can run in the browser.

So I tried it on Juggling Lab, and it [works fairly well](https://jugglinglab.karavia.ch/)!

The source code is [here](https://github.com/rkaravia/jugglinglab-cheerpj), feel free to use it in any way you would like. Anyway I just followed the [CheerpJ Tutorial](https://github.com/leaningtech/cheerpj-meta/wiki/Tutorial) and added a few lines of HTML.

**Comment by jkboyce** [comment]
@rkaravia Thanks for letting me know about this! This is really cool technology. I'm hosting it now on a page at [jugglinglab.org](https://jugglinglab.org/html/run.html). I've also put you in the site credits, I hope that's ok with you.

You can't save or load files to the local filesystem of course. The only thing I see that doesn't work is the contextual menu that is supposed to pop up with a right-click in the ladder diagram part of the "Visual editor" view. Not a huge deal but I may do some digging to figure out what's going on.

Thanks again. :+1:

**Comment by rkaravia** [comment]
Awesome, I'm very happy this made it to jugglinglab.org :-)

**Comment by jkboyce** [comment]
It turns out the issue with popup menus is Mac-specific: Control-click is not recognized as a right mouse click. A workaround is to use a two-button mouse or enable "secondary click" on the Mac's trackpad. Filed an [issue](https://github.com/leaningtech/cheerpj-meta/issues/80) with the CheerpJ team to make them aware.
