### ISSUE TITLE
No documentation about "!"

### ISSUE THREAD

**Issue by hapiel** [jkboyce/jugglinglab#96]
I believe there is no documentation about what `!` is used for in the siteswap notations.

I have come to work it out as it being a short synch throw that takes only 1 beat rather than 2 beats? So `(4,4)` equals `(4,4)!(0,0)!`, which allows the possibilities to create patterns such as `(5,5)(5x,5x)(0,0)!`. Is my understanding correct? Perhaps it should be noted somewhere on https://jugglinglab.org/html/ssnotation.html

**Comment by jkboyce** [comment]
Great catch @hapiel – I didn't realize this wasn't documented anywhere. I'll do that.

**Comment by jkboyce** [comment]
Updated https://jugglinglab.org/html/ssnotation.html to include documentation of short-beat sync throws, and clarified the explanation of async hand assignment.
